# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DM <- function(Y, alpha) {
    .Call('_BDMMA_DM', PACKAGE = 'BDMMA', Y, alpha)
}

DM_diff <- function(Y, alpha1, alpha2, g) {
    .Call('_BDMMA_DM_diff', PACKAGE = 'BDMMA', Y, alpha1, alpha2, g)
}

update_alpha2 <- function(alpha, alpha_m, x, y, beta, T, lambda, prop, delta_m) {
    .Call('_BDMMA_update_alpha2', PACKAGE = 'BDMMA', alpha, alpha_m, x, y, beta, T, lambda, prop, delta_m)
}

update_beta1 <- function(alpha_m, x, y, beta, T, L, sigma1, eta, delta_m) {
    .Call('_BDMMA_update_beta1', PACKAGE = 'BDMMA', alpha_m, x, y, beta, T, L, sigma1, eta, delta_m)
}

update_beta <- function(alpha_m, x, y, beta, T, K, sigma2, delta_m) {
    .Call('_BDMMA_update_beta', PACKAGE = 'BDMMA', alpha_m, x, y, beta, T, K, sigma2, delta_m)
}

update_delta <- function(alpha_m, x, y, delta, delta_m, beta, e_delta, batch, N, T, I, sigma3) {
    .Call('_BDMMA_update_delta', PACKAGE = 'BDMMA', alpha_m, x, y, delta, delta_m, beta, e_delta, batch, N, T, I, sigma3)
}

Mat_To_Rowvec <- function(m) {
    .Call('_BDMMA_Mat_To_Rowvec', PACKAGE = 'BDMMA', m)
}

MCMC <- function(alpha, alpha_m, x, y, beta, delta, delta_m, e_delta, T, N, K, I, lambda, prop, L, sigma1, sigma2, sigma3, iter, eta, a, b, p, batch) {
    .Call('_BDMMA_MCMC', PACKAGE = 'BDMMA', alpha, alpha_m, x, y, beta, delta, delta_m, e_delta, T, N, K, I, lambda, prop, L, sigma1, sigma2, sigma3, iter, eta, a, b, p, batch)
}

